plugins {
  id 'java'
  id 'application'
  id 'org.openjfx.javafxplugin' version '0.0.13'
  id 'org.beryx.jlink' version '2.25.0'
}

// jar {
//   // Exclude manifest files from all dependencies
//   from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } } {
//     exclude 'META-INF/*.MF' // Exclude all manifest files
//   }
// }



group 'com.hottes.caleb'
version '1.0-SNAPSHOT'

repositories {
  mavenCentral()
}

ext {
  junitVersion = '5.10.2'
}

sourceCompatibility = '22'
targetCompatibility = '22'

tasks.withType(JavaCompile) {
  options.encoding = 'UTF-8'
}

application {
  //mainModule = 'com.hottes.caleb.ultimateticktacktoe'
  mainClass = 'com.hottes.caleb.ultimateticktacktoe.Launcher'
}

javafx {
  version = '22.0.1'
  modules = ['javafx.controls', 'javafx.fxml', 'javafx.swing']
}

dependencies {
  implementation('org.controlsfx:controlsfx:11.2.1')

  testImplementation("org.junit.jupiter:junit-jupiter-api:${junitVersion}")
  testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:${junitVersion}")

  // https://mvnrepository.com/artifact/org.json/json
  implementation group: 'org.json', name: 'json', version: '20240303'
// https://mvnrepository.com/artifact/org.junit.platform/junit-platform-suite
  implementation group: 'org.junit.platform', name: 'junit-platform-suite', version: '1.11.0'
// https://mvnrepository.com/artifact/org.openjdk.jol/jol-core
  implementation group: 'org.openjdk.jol', name: 'jol-core', version: '0.17'


//----------working------------
  // https://mvnrepository.com/artifact/org.nd4j/nd4j-native-platform
  implementation group: 'org.nd4j', name: 'nd4j-native-platform', version: '1.0.0-M2.1'

  // https://mvnrepository.com/artifact/org.deeplearning4j/deeplearning4j-core
  //implementation group: 'org.deeplearning4j', name: 'deeplearning4j-core', version: '1.0.0-M2.1'

  implementation('org.deeplearning4j:deeplearning4j-core:1.0.0-M2.1') {
      exclude(group: 'ffmpeg-5.0-1.5.7-android-arm.jar')
  }

// https://mvnrepository.com/artifact/org.deeplearning4j/deeplearning4j-ui
  implementation group: 'org.deeplearning4j', name: 'deeplearning4j-ui', version: '1.0.0-M2.1'


// https://mvnrepository.com/artifact/ch.qos.logback/logback-classic
  implementation group: 'ch.qos.logback', name: 'logback-classic', version: '1.5.9'


  //------------------------experimental----------------------
  implementation group: 'com.github.sh0nk', name: 'matplotlib4j', version: '0.5.0'

  // https://mvnrepository.com/artifact/com.opencsv/opencsv
  implementation group: 'com.opencsv', name: 'opencsv', version: '5.9'

  implementation 'org.apache.commons:commons-math3:3.6.1'


//  // https://mvnrepository.com/artifact/org.nd4j/nd4j-cuda-10.0-platform
//  implementation group: 'org.nd4j', name: 'nd4j-cuda-11.4', version: '1.0.0-M2.1'
//
//
////  // https://mvnrepository.com/artifact/org.nd4j/nd4j-native-platform
////  implementation group: 'org.nd4j', name: 'nd4j-native-platform', version: '1.0.0-M2.1'
//
//  // https://mvnrepository.com/artifact/org.deeplearning4j/deeplearning4j-core
//  implementation group: 'org.deeplearning4j', name: 'deeplearning4j-core', version: '1.0.0-M2.1'
//
//// https://mvnrepository.com/artifact/org.deeplearning4j/deeplearning4j-ui
//  implementation group: 'org.deeplearning4j', name: 'deeplearning4j-ui', version: '1.0.0-M2.1'



  //------------------------experimental----------------------


}

test {
useJUnitPlatform()}

jlink {
  imageZip = project.file("${buildDir}/distributions/app-${javafx.platform.classifier}.zip")
  options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
  launcher {
    name = 'app'
  }
}

jlinkZip {
  group = 'distribution'
}
// jar {
//   // Use a custom manifest file you created
//   manifest {
//     attributes(
//             'Main-Class': 'com.hottes.caleb.ultimateticktacktoe.Launcher'  // replace with your main class
//     )
//   }

//   // Exclude all manifests from dependencies
//   from(configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }) {
//     exclude 'META-INF/MANIFEST.MF'
//   }
//   duplicatesStrategy = DuplicatesStrategy.INCLUDE  // Keeps the first occurrence of duplicate entries



// }

