package com.hottes.caleb.ultimateticktacktoe;


import com.hottes.caleb.ultimateticktacktoe.gameindependant.GameAction;
import com.hottes.caleb.ultimateticktacktoe.gameindependant.GameState;
import com.hottes.caleb.ultimateticktacktoe.ui.UltimateTickTacToeGameAction;

import java.awt.*;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.BitSet;

import static com.hottes.caleb.ultimateticktacktoe.Resources.getIndex;

/**
 * Board state represents a state of an ultimate tick tac toe board. It is square and has a board size. so far only a board size of three has been used, but the code is hopefully able to support larger sizes too.
 * this class contains various ways to create boards states and methods to manipulate them. There are getters and constructors for string hashes and bit sets. These are used to store board states in a memory efficient manner.
 * The string hash method has been deprecated in favor of the bit set method.
 */
public class BoardState extends GameState {

    private final int boardSize;



    private final SubBoardState[][] minorBoards;

    private final Rectangle2D.Double[][] subBoardBoundingBoxes;

    /**
     * creates a new empty major board
     * @param theBoardSize must be at least 1
     */
    public BoardState(int theBoardSize) {
        super(theBoardSize, theBoardSize);
        this.boardSize = theBoardSize;
        this.minorBoards = new SubBoardState[theBoardSize][theBoardSize];
        this.subBoardBoundingBoxes = new Rectangle2D.Double[boardSize][boardSize];
        for (int i = 0; i < minorBoards.length; i++) {
            for (int j = 0; j < minorBoards[0].length; j++) {
                this.minorBoards[i][j] = new SubBoardState(boardSize);
            }

        }
    }

    /**
     * creates a board state from an inital state
     * @param minorBoardsInit the inital state
     * @param theBoardSize the board size
     */
    public BoardState(SubBoardState[][] minorBoardsInit, int theBoardSize) {
        super(theBoardSize, theBoardSize);
        this.boardSize = theBoardSize;
        this.minorBoards = minorBoardsInit;
        this.subBoardBoundingBoxes = new Rectangle2D.Double[boardSize][boardSize];
    }

    /**
     * creates a board state from a string hash
     * @param hash the string hash
     */
    @Deprecated
    public BoardState(String hash) {
        this(hash.split("\\$"));
    }

    /**
     * this code worked first try!
     * Constructs a board state from a bit set generated by the get bit set method below
     * @param bitSet the bitset to construct the board state from
     */
    public BoardState(BitSet bitSet) {
        super(bitSet.toByteArray()[0]);
        boardSize = bitSet.toByteArray()[0];
        this.subBoardBoundingBoxes = new Rectangle2D.Double[boardSize][boardSize];
        this.minorBoards = new SubBoardState[boardSize][boardSize];
        int index = 8;
        //decode whose turn it is
        boolean playerOneTurn = bitSet.get(index);
        index++;
        int numcells = boardSize * boardSize;
        for (int row = 0; row < boardSize; row++) {
            for (int col = 0; col < boardSize; col++) {
                //for each board
                boolean isActive = bitSet.get(index);
                index++;
                double[][] state = new double[boardSize][boardSize];
                for (int minorRow = 0; minorRow < boardSize; minorRow++) {
                    for (int minorCol = 0; minorCol < boardSize; minorCol++) {
                        if (bitSet.get(index)) {
                            //if there is a marker here
                            state[minorRow][minorCol] = bitSet.get(index + numcells)?1:-1;
                        }else {
                            state[minorRow][minorCol] = 0;
                        }
                        index++;
                    }

                }
                index+=numcells;
                minorBoards[row][col] = new SubBoardState(state, isActive, boardSize);

            }
        }
        setPlayerOneTurn(playerOneTurn);


    }

    //called from the other constructor, two constructors because I have to call super or this right away
    private BoardState (String[] hashTokens) {
        super(Integer.parseInt(hashTokens[0]));
        this.boardSize = Integer.parseInt(hashTokens[0]);
        this.subBoardBoundingBoxes = new Rectangle2D.Double[boardSize][boardSize];
        this.minorBoards = new SubBoardState[boardSize][boardSize];
        for (int row = 0; row < boardSize; row++) {
            for (int col = 0; col < boardSize; col++) {
                minorBoards[row][col] = new SubBoardState(hashTokens[(row * boardSize) + col + 1]);
            }
        }
    }

    /**
     * during testing this method cut memory size from 3328 bytes/BoardState to 128
     * @return a string representing this board state
     */

    @Override
    @Deprecated
    public String getStringHash() {
        StringBuilder builder = new StringBuilder();
        builder.append(boardSize);
        for (SubBoardState[] row: minorBoards) {
            for (SubBoardState subBoardState : row) {
                builder.append("$").append(subBoardState.getStringHash());
            }
        }
        return builder.toString();

    }

    /**
     * format for the bitset data storage is as follows.
     * the first 8 bits are a byte representing the board size.
     * the next bit represents whose turn it is
     * then each suboard is represented by 19 bits. they are indexed from the top left row first. so the top right is 2, and the bottom left is 6
     * for each of the sub boards the first bit of the 19 represents whether it is active or not. Then the next 9 bits represent if each of the cells contain anything. 0 if empty, 1 if either X or O
     * the last 9 bits for each subboard represent whether each cell is occupied by player one (1) so 0 if the cell is 0 or -1 and 1 if the cell is 1
     * @return a bitset representing this board state
     */
    public BitSet getBitSet() {
        int numcells = boardSize * boardSize;
        BitSet output = new BitSet(9 + numcells + 2 * numcells * numcells);
        output.or(BitSet.valueOf(new byte[]{(byte) boardSize}));
        int index = 8;
        //add in whose turn it is
        output.set(index, isPlayerOneTurn());
        index++;
        for (SubBoardState[] row: minorBoards) {
            for (SubBoardState subBoardState : row) {
                //for each minor board
                //add if its active

                output.set(index, subBoardState.isActive());
                index++;

                for (int minorRow = 0; minorRow < boardSize; minorRow++) {
                    for (int minorCol = 0; minorCol < boardSize; minorCol++) {
                        //add if each cell is filled
                        output.set(index, subBoardState.itemAt(minorRow, minorCol) != 0);
                        //add if this cell is occupied by player one
                        output.set(index + numcells, subBoardState.itemAt(minorRow, minorCol) == 1);
                        index++;
                    }

                }
                index += numcells;

            }
        }
        return output;
    }


    /**
     * used for machine learning
     * returns a vector representing the state of this board.
     * the player whose turn it is will be represented by the number 1 and the other player will be -1.
     * so the board may be inverted. This method will also append on the end of the array a some 1's or -1's to represent
     * which sub boards are active. So for each index 1 means active and -1 not. The reason why  not 0 and 1 it for ML normalzation, i want to
     * keep all the values between 1 and -1 and a boolean ought to be on the extremes
     * takes aroung 2us to execute.
     * @return a double[] of numbers representing the state of the board and which boards are active.
     */
    public double[] getValueNetworkInputVector() {
        double[] output = new double[ (int) Math.round(Math.pow(boardSize, 4) + (boardSize * boardSize))];//enough space for a number for each of the cells on the board and one more number to represent the activity of each sub board.
        for (int majRow = 0; majRow < boardSize; majRow++) {
            for (int majCol = 0; majCol < boardSize; majCol++) {
                output[getIndex(boardSize - 1, boardSize - 1, boardSize - 1, boardSize -1 , boardSize) + 1 + (majRow * boardSize) + majCol] = getMinorBoardAt(majRow, majCol).isActive()?1:-1;
                for (int minRow = 0; minRow < boardSize; minRow++) {
                    for (int minCol = 0; minCol < boardSize; minCol++) {
                        output[getIndex(majRow, majCol, minRow, minCol, boardSize)] = isPlayerOneTurn()?getMinorBoardAt(majRow, majCol).itemAt(minRow, minCol):-getMinorBoardAt(majRow, majCol).itemAt(minRow, minCol);//make sure the player who is to play is represented by 1's
                                            }
                }

            }
        }
        return output;
    }


    /**
     * updates the superclass state variable to match the evaluations of the sub boards
     */
    private void updateState() {
        for (int i = 0; i < boardSize; i++) {
            for (int j = 0; j < boardSize; j++) {
                state[i][j] = minorBoards[i][j].getEvaluation();
            }
        }
    }

    /**
     *
     * Evaluations are 1 for player 1 wins, -1 for player 1 loses, 0 for intederminate state and -.25 for draw
     *
     * @return the static evaluation of the game state
     */
    @Override
    public double getEvaluation() {
        updateState();
        return Resources.getTicTacToeEvaluationBruteForce(state);
    }

    /**
     * returns a list of ultimate tick tack toe actions that are legal
     * @return a list of legal actions that can be taken by player 1 in this scenario
     */
    @Override
    public ArrayList<GameAction> getActions() {
        ArrayList<GameAction> actions = new ArrayList<>();
        for (int i = 0; i < state.length; i++) {
            for (int j = 0; j < state[0].length; j++) {
                if (minorBoards[i][j].isActive()) {
                    for (GameAction subAction : minorBoards[i][j].getActions()) {
                        actions.add(new UltimateTickTacToeGameAction(i, j, subAction.x, subAction.y, 1));
                    }
                }
            }
        }
        return actions;
    }

    /**
     * tests if a given UTT game action is legal on this state.
     * this method does care about the marker.
     * @param action the action to be tested
     * @return true if the action is legal
     */
    public boolean isLegal(UltimateTickTacToeGameAction action) {
        if ((isPlayerOneTurn() && action.getMarker() == -1) || (!isPlayerOneTurn() && action.getMarker() == 1)) {
            //then we have the wrong marker.
            return false;
        }
        if (!minorBoards[action.getMajorRow()][action.getMajorCol()].isActive()) {
            //if the board is not active.
            return false;
        }
        return minorBoards[action.getMajorRow()][action.getMajorCol()].itemAt(action.y, action.x) == 0;
    }

    /**
     * inverts the state of the board and all its minor boards.
     * it also flips whose turn it is.
     */
    @Override
    public void invertState() {
        for (int i = 0; i < state.length; i++) {
            for (int j = 0; j < state[i].length; j++) {
                state[i][j] = state[i][j] * -1;
            }
        }
        togglePlayerOneTurn();
        for (int i = 0; i < minorBoards.length; i++) {
            for (int j = 0; j < minorBoards[0].length; j++) {
                getMinorBoardAt(i, j).invertState();
            }
        }
    }


    /**
     * renders an image of the current state of the board
     * The height and width used are arbitrary as the image view will rescale the image to the correct size before displaying it.
     * @return a buffered image representing the board
     */
    public BufferedImage getRenderedImage(double width, double height) {
        if (width <= 0) {
            width = 1;
        }
        if (height <= 0) {
            height = 1;
        }
        BufferedImage output = new BufferedImage((int) Math.round(width), (int) Math.round(height), BufferedImage.TYPE_INT_ARGB);
        Graphics2D g = (Graphics2D) output.getGraphics();
        //all math done with doubles, rounded at the last possible moment
        double horizontalSpacing = width * Resources.HORIZONTAL_SPACING_FACTOR;
        double verticalSpacing = height * Resources.VERTICAL_SPACING_FACTOR;

        double subBoardWidth = (width - (boardSize + 1) * horizontalSpacing)/boardSize;
        double subBoardHeight = (height - (boardSize + 1) * verticalSpacing)/boardSize;

        for (int i = 0; i < boardSize; i++) {
            for (int j = 0; j < boardSize; j++) {
                Rectangle2D.Double subBoardBoundingBox = new Rectangle2D.Double((horizontalSpacing * (i + 1)) + (subBoardWidth * i),(verticalSpacing * (j + 1)) + (subBoardHeight * j) ,subBoardWidth,subBoardHeight);
                subBoardBoundingBoxes[j][i] = subBoardBoundingBox;
                minorBoards[j][i].render(g, subBoardBoundingBox);
            }
        }




        return output;
    }

    /**
     * checks that the argument is both a UTT action and is legal.
     * preforms the specified ultimate tick tack toe action on the board, sets the relvant boards active and toggles whose turn it is
     * @param action the action to preform
     * @throws IllegalArgumentException if the action is not an instance of UltimateTickTacToeGameAction or if the action is illegal
     */
    @Override
    public void preformAction(GameAction action) {
        if (!(action instanceof UltimateTickTacToeGameAction)) {
            throw new IllegalArgumentException("Invalid game action received: Action must be for a tic tac toe board");
        }
        //it is assumed that the move is legal so place the marker, (DLL injection cheat possible here?)
        if (!isLegal((UltimateTickTacToeGameAction) action)) {
            throw new IllegalArgumentException("Illegal game action received!");
        }
        int majorRow = ((UltimateTickTacToeGameAction) action).getMajorRow();
        int majorCol = ((UltimateTickTacToeGameAction) action).getMajorCol();
        this.minorBoards[majorRow][majorCol].preformAction(action);
        //flip whose turn it is
        togglePlayerOneTurn();
        //set the activity of the boards
        setAllBoardsActivity(false);
        SubBoardState boardToSendTo = this.minorBoards[action.y][action.x];
        if (boardToSendTo.getEvaluation() != 0) {
            //if somebody has won this board or it has been drawn
            //then we need to set all non won boards active
            for (int i = 0; i < boardSize; i++) {
                for (int j = 0; j < boardSize; j++) {
                    this.minorBoards[i][j].setActive(this.minorBoards[i][j].getEvaluation() == 0);
                }
            }
        }else {
            boardToSendTo.setActive(true);
        }

    }


    //make sure preserves whose turn it is

    /**
     * simulates a game action and returns a Game state with this action preformed on it.
     * does not affect this board state
     * @param action the action to be simulated
     * @param invertBoard multiplies the state by -1 before returning
     * @return a BoardState
     */
    @Override
    public GameState simulateAction(GameAction action, boolean invertBoard) {
         BoardState newState = new BoardState(getMinorBoardsCopy(), boardSize);
         newState.setPlayerOneTurn(isPlayerOneTurn());
         newState.preformAction(action);
         if (invertBoard) {
             newState.invertMinorBoards();
         }
         return newState;
    }

    /**
     * creates a complete copy of this board state with no pointers.
     * @return a copy of the board state.
     */
    public BoardState getClone() {
        BoardState clone = new BoardState(getMinorBoardsCopy(), boardSize);
        clone.setPlayerOneTurn(isPlayerOneTurn());
        return clone;
    }

    /**
     * used for two player games.
     * @param action the proposed game action
     * @return if the move is legal
     */
    @Override
    public boolean isMoveLegal(GameAction action) {
        if (!(action instanceof UltimateTickTacToeGameAction)) {
            return false;
        }
        SubBoardState minorBoard = minorBoards[((UltimateTickTacToeGameAction) action).getMajorRow()][((UltimateTickTacToeGameAction) action).getMajorCol()];
        if (!minorBoard.isActive()) {
            //if the board we are trying to play on is not active
            return false;
        }
        if ((isPlayerOneTurn() && (action.getMarker() != 1)) || (!isPlayerOneTurn() && (action.getMarker() != -1))) {
            //then the player marker does not align with whose turn it is
            return false;
        }
        return minorBoard.isMoveLegal(action);
    }

    /**
     * Sets all boards to the speficied acitivity value
     * @param val the bool to set the activity of the boards to
     */
    public void setAllBoardsActivity(boolean val) {
        for (SubBoardState[] minorBoard : minorBoards) {
            for (SubBoardState subBoardState : minorBoard) {
                subBoardState.setActive(val);
            }
        } 
    }

    /**
     * sets the speified board active and all the rest inactive
     * @param row the row
     * @param column the column
     */
    public void setBoardActive(int row, int column) {
        for (SubBoardState[] minorBoard : minorBoards) {
            for (SubBoardState subBoardState : minorBoard) {
                subBoardState.setActive(false);
            }
        } 
        minorBoards[row][column].setActive(true);
    }



    public Rectangle2D.Double[][] getSubBoardBoundingBoxes() {
        return subBoardBoundingBoxes;
    }

    /**
     * inverts the minor boards
     */
    public void invertMinorBoards() {
        for (SubBoardState[] minorBoard : minorBoards) {
            for (int j = 0; j < minorBoards[0].length; j++) {
                minorBoard[j].invertState();
            }
        }
    }


    /**
     * copies the sub boards into a new array using the copy method in subboard state.
     * you can change the copied array without affecting this state.
     * @return a copy of the minor boards
     */
    public SubBoardState[][] getMinorBoardsCopy() {
        SubBoardState[][] output = new SubBoardState[boardSize][boardSize];
        for (int i = 0; i < minorBoards.length; i++) {
            for (int j = 0; j < minorBoards[0].length; j++) {
                output[i][j] = new SubBoardState(minorBoards[i][j].getStateAsCopy(), minorBoards[i][j].isActive(), boardSize);
            }
        }
        return output;
    }

    /**
     * returns the sub board at the specified position
     * @param row the row
     * @param col the col
     * @return the sub board.
     */
    public SubBoardState getMinorBoardAt(int row, int col) {
        return minorBoards[row][col];
    }
    /**
     *
     * @return the minor board variable
     */
    public SubBoardState[][] getMinorBoards() {
        return minorBoards;
    }


    @Override
    public String toString() {
        DecimalFormat format = new DecimalFormat(" .;-.");
        StringBuilder builder = new StringBuilder();
        builder.append("\n");
        for (int majorRow = 0; majorRow < boardSize; majorRow++) {
            for (int minorRow = 0; minorRow < boardSize; minorRow++) {
                for (int majorCol = 0; majorCol < boardSize; majorCol++) {
                    for (int minorCol = 0; minorCol < boardSize; minorCol++) {
                        builder.append("|").append(minorBoards[majorRow][majorCol].isActive()?"*":" ").append(format.format(minorBoards[majorRow][majorCol].itemAt(minorRow, minorCol))).append(" ");
                    }
                    builder.append("|");

                }
                builder.append("\n");
            }
            if (majorRow != boardSize - 1) {
                builder.append("|=====+=====+=====||=====+=====+=====||=====+=====+=====|\n");
            }else {
                builder.append("\n");
            }
        }
        return builder.toString();
    }
}
