package com.hottes.caleb.ultimateticktacktoe.gameindependant;

import com.hottes.caleb.ultimateticktacktoe.Resources;

import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.BitSet;

/**
 * Represents a state of a Monte Carlo Tree Searchable game and provides methods to be implemented for any specific game.
 * This class works for 2 player tune based non random determinisic games that are played on 2 dimenisional boards and contain pieces for each player.
 * For any given state the player whose turn it is to play is represented by postiive values, and the opponent is negative. If  a square is empty then it contains a zero.
 */
public abstract class GameState {

    protected final double[][] state;

    private final int rows;
    private final int cols;



    private boolean isPlayerOneTurn = true;


    public GameState(int boardSize) {
        this(boardSize, boardSize);
    }

    /**
     * Creates an empty game state
     *
     * @param rows
     * @param columns
     */
    public GameState(int rows, int columns) {
        state = new double[rows][columns];
        this.rows = rows;
        this.cols = columns;
    }

    /**
     * constructs an arbitrary state
     *
     * @param theState
     */
    public GameState(double[][] theState) {
        state = theState;
        this.rows = state.length;
        this.cols = state[0].length;
    }

    /**
     * constructs a game state from a hash generated by the approriate function below.
     * @param hash
     */
    public GameState (String hash) {
        String[] tokens = hash.split("#");
        rows = Integer.parseInt(tokens[0]);
        cols = Integer.parseInt(tokens[1]);
        String stateString = Integer.toString(Integer.parseInt(tokens[2], 10), 4);
        ArrayList<Integer> nums = new ArrayList<>();
        for (String token : stateString.split("")) {
            nums.add(Integer.parseInt(token) - 2);
        }
        state = new double[rows][cols];
        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < cols; j++) {
                state[i][j] = nums.get((i * cols) + j);
            }
        }
    }


    @Override
    public String toString() {
        StringBuilder strToReturn = new StringBuilder();
        for (double[] row : state) {
            strToReturn.append("|");
            for (double val : row) {
                strToReturn.append(" ").append(val).append(" |");
            }
            strToReturn.append(" \n");
        }
        return strToReturn.toString();
    }

    /**
     * returns a string representation of this object which can be parsed by the string constructor
     * uses # for delimiter. Contains the number of row, cols and the fast hashcode.
     * @return
     */
    public String getStringHash() {

        return rows + "#" + cols + "#" + Resources.fastTicTacToeHashcode(state);

    }

    /**
     * Evaulates the state and retuens a number between 1 and -1 this could be simple logic or
     * For chess it could be the output of a neural network.
     *1 means that the state is good for player 1 and -1 means that the state is bad for player 1
     * @return static evaluation of game state
     */
    public abstract double getEvaluation();


    /**
     * Assumes that the place on the board must be empty in order to move there, (for games like tick tack toe and GO?)
     * Should be overridden for games like chess and checkers
     *
     * @return a list of valid Game Actions that the current player can take
     */
    public ArrayList<GameAction> getActions() {
        ArrayList<GameAction> actions = new ArrayList<>();
        for (int i = 0; i < state.length; i++) {
            for (int j = 0; j < state[i].length; j++) {
                if (state[i][j] == 0.0) {
                    actions.add(new GameAction(i, j));
                }
            }
        }
        return actions;
    }

    public abstract BitSet getBitSet();


    /**
     * This method tries to set the value in the state array at the speficifed location to the marker value
     * If the action is not on the board, ie < 0 or >m board size then a normal arrayindex out of bounds is thrown
     * This method does NOT check if the action is legal according the the games rules
     * this method is itended to do whatever is nessacary to prepare the board for the next move. that could mean
     * flipping whose turn it is, changing custom properties of the board etc.
     *
     * @param action
     * @throws ArrayIndexOutOfBoundsException if the action is not on the board,
     */
    public void preformAction(GameAction action) throws ArrayIndexOutOfBoundsException {
        this.state[action.y][action.x] = action.getMarker();
    }

    /**
     * preforms the action on a differnet state and returns a new state object with this action preformed
     *
     * @param action
     * @param invertBoard multiplies the state by -1 before returning
     * @return
     */
    public abstract GameState simulateAction(GameAction action, boolean invertBoard);

    /**
     * implements the rules of the game and determines if the move is legal to be played on this board
     * @param action the proposed game action
     * @return if the move is legal
     */
    public abstract boolean isMoveLegal(GameAction action);

    public double[][] getStateAsCopy() {
        double[][] output = new double[state.length][state[0].length];
        for (int i = 0; i < state.length; i++) {
            System.arraycopy(state[i], 0, output[i], 0, state[0].length);
        }
        return output;
    }

    public void invertState() {
        for (int i = 0; i < state.length; i++) {
            for (int j = 0; j < state[i].length; j++) {
                state[i][j] = state[i][j] * -1;
            }
        }
        isPlayerOneTurn = !isPlayerOneTurn;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        GameState gameState = (GameState) o;
        return Arrays.deepEquals(state, gameState.state);
    }

    public String getSHAHash() {
        MessageDigest md = null;
        try {
            md = MessageDigest.getInstance("SHA-256");
        } catch (NoSuchAlgorithmException e) {
            return String.valueOf(hashCode());
        }

        byte[] rawHash =  md.digest(Arrays.deepToString(state).getBytes(StandardCharsets.UTF_8));
        BigInteger number = new BigInteger(1, rawHash);
        StringBuilder hexString = new StringBuilder(number.toString(16));
        while (hexString.length() < 64) {
            hexString.insert(0, '0');
        }
        return hexString.toString();
    }

    public int getRows() {
        return rows;
    }

    public int getCols() {
        return cols;
    }

    public double itemAt(int row, int column) {
        return state[row][column];
    }

    public boolean isPlayerOneTurn() {
        return isPlayerOneTurn;
    }
    //for testing only
    public void setPlayerOneTurn(boolean playerOneTurn) {
        isPlayerOneTurn = playerOneTurn;
    }

    public void togglePlayerOneTurn() {
        isPlayerOneTurn = !isPlayerOneTurn;
    }

}
